-- 코드를 입력하세요
WITH T AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND NOT EXISTS(
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE H.CAR_ID = C.CAR_ID 
        AND (
            H.START_DATE <= '2022-11-30'
            AND H.END_DATE >= '2022-11-01'
        )
    )
)

SELECT T.CAR_ID, T.CAR_TYPE,
        ROUND(T.DAILY_FEE * 30 * (1 - CAST(REPLACE(P.DISCOUNT_RATE, '%', '') AS DECIMAL)/100), 0) AS FEE
FROM T T
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON T.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
WHERE T.DAILY_FEE * 30 * (1 - CAST(REPLACE(P.DISCOUNT_RATE, '%', '') AS DECIMAL)/100) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;

