WITH T AS 
(SELECT ID, 
    RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) rnk,
    COUNT(*) OVER() AS COUNT
 FROM ECOLI_DATA)
 
SELECT ID, 
    CASE WHEN (rnk <= COUNT * 0.25) THEN 'CRITICAL'
        WHEN (rnk <= COUNT * 0.5) THEN 'HIGH'
        WHEN (rnk <= COUNT * 0.75) THEN 'MEDIUM'
        ELSE 'LOW'
        END AS COLONY_NAME
FROM T
ORDER BY ID;
 