-- 코드를 입력하세요

With F AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF
    GROUP BY FLAVOR
), J AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY
    GROUP BY FLAVOR
)

SELECT FLAVOR
FROM F JOIN J using(FLAVOR)
ORDER BY (F.TOTAL + J.TOTAL) DESC
LIMIT 3;