-- 코드를 작성해주세요
SELECT M.YEAR AS YEAR, M.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA E
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
      MAX(SIZE_OF_COLONY) AS MAX_SIZE
      FROM ECOLI_DATA
        GROUP by YEAR(DIFFERENTIATION_DATE)) M
ON M.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV;
