-- 코드를 입력하세요
SELECT UGB.TITLE, UGB.BOARD_ID, UGP.REPLY_ID, UGP.WRITER_ID
        , UGP.CONTENTS, DATE_FORMAT(UGP.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD AS UGB, USED_GOODS_REPLY AS UGP
WHERE UGB.BOARD_ID = UGP.BOARD_ID
    AND DATE_FORMAT(UGB.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY UGP.CREATED_DATE, UGB.TITLE;